<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DELL" failures="3" tests="4" name="LoginTest" time="41.511" errors="0" timestamp="2025-06-08T15:24:21 IST">
  <testcase classname="tests.LoginTest" name="LoginMethod" time="9.862">
    <failure type="java.lang.AssertionError" message="Login failed – invalid credentials or error">
      <![CDATA[java.lang.AssertionError: Login failed – invalid credentials or error
at tests.LoginTest.LoginMethod(LoginTest.java:58)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginMethod -->
  <testcase classname="tests.LoginTest" name="LoginMethod" time="9.418">
    <failure type="java.lang.AssertionError" message="Login failed – invalid credentials or error">
      <![CDATA[java.lang.AssertionError: Login failed – invalid credentials or error
at tests.LoginTest.LoginMethod(LoginTest.java:58)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginMethod -->
  <testcase classname="tests.LoginTest" name="LoginMethod" time="8.416">
    <failure type="java.lang.AssertionError" message="Login failed – invalid credentials or error">
      <![CDATA[java.lang.AssertionError: Login failed – invalid credentials or error
at tests.LoginTest.LoginMethod(LoginTest.java:58)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginMethod -->
  <testcase classname="tests.LoginTest" name="LoginMethod" time="7.779"/>
</testsuite> <!-- LoginTest -->
